name: composite
description: composite action
inputs:
  role:
    description: role
    required: true
  duration:
    description: how long
    required: true
outputs:
  junk:
    description: outputs
    value: ${{ steps.go.outputs.out }}
runs:
  using: composite
  steps:
    - id: go
      run: go run action.go
      shell: bash

