name: composite

on: 
  workflow_dispatch:
    inputs:
      role:
        description: role
        required: true
        type: string
      duration:
        description: how long
        required: true
        type: string

jobs:
  composite:
    runs-on: ubuntu-latest
    name: composite
    steps:
      - uses: actions/checkout@v4
      - id: foo
        uses: mattkasun/test/.github/actions/composite@master
        with:
         role: ${{ inputs.role }}
         duration: $(( inputs.duration ))
