name: Debugging

on:
  pull_request:
    branches:
      - master
    types: [closed]
  workflow_dispatch:
    inputs:
      tag:
        description: 'docker tag'
        required: true
  workflow_call:
    inputs:
      tag:
        required: true
        type: string

jobs:
  getserver:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get server
        run: |
          echo "server=${{ github.event.inputs.tag }} >>$GITHUB_ENV"
          echo ${{ github.event.inputs.tag }} >> /tmp/server
      - name: Upload server
        uses: actions/upload-artifact@v2
        with:
          name: server
          path: /tmp/server
          retention-days: 1

