name: Debug Call

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'docker tag'
        required: true

jobs:
  x86:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Set tag
        run: |
            if [[ -n "${{ inputs.tag }}" ]]; then
              TAG=${{ inputs.tag }}
            elif [[ "${{ github.ref_name }}" == 'master' ]]; then
              TAG="latest"
            else
              TAG="${{ github.ref_name }}"
            fi
            echo "TAG=${TAG}" >> $GITHUB_ENV
      - 
        name: echo
        run: |
         echo ${{ env.TAG }}
  call:
    uses: ./.github/workflows/debug.yml
    with:
      tag: ${{ inputs.tag }}
    secrets: inherit    

