name: Discord

on:
  workflow_run:
    workflows: [Go]
    types:
      - completed
jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclustion == success  }}
    steps:
      - name: discord success message
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.DISCORD_WEBHOOK_ID }}
          webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
          color: "#42f545"
          username: "GitHub Bot"
          message: "${{ github.event.workflow_run }} was successful"

      - name: discord fail message
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.DISCORD_WEBHOOK_ID }}
          webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
          color: "#990000"
          username: "GitHub Bot"
          message: "${{ github.event.workflow_run }} failed"
