name: Test Go Action

on: 
    workflow_dispatch:
        inputs:
            masterkey:
                description: server masterkey
                type: string
            cmd_args:
                description: args for test command
                type: string
                required: true
    
jobs:
    run:
        runs-on: ubuntu-latest
        steps:
        - name: invoke go action
          uses: mattkasun/test/.github/actions/test-action@master
          with:
            MASTERKEY: ${{ inputs.masterkey }}
            cmd_args: ${{ inputs.cmd_args }}
          env:
            DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_TOKEN }}
            MASTERKEY: ${{ inputs.masterkey }}
    docker:
        runs-on: ubuntu-latest
        steps:
        - name: docker
          uses: mattkasun/test/.github/actions/docker-action@master
          env:
            DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_TOKEN }}
            MASTERKEY: ${{ inputs.masterkey }}
            KEY: ${{ secrets.TESTING_SSH_KEY }}


