name: Test Go Action

on:
    workflow_dispatch:
        inputs:
          tag:
            required: true
            description: DO tag to use for testing
            default: "devops"
          network: 
            description: network to use for testing
            required: true
            default: "devops"
          api:
            description: api endopoint to use for testing
            required: true
            default: "https://api.clustercat.com"
          masterkey:
            description: master key of server
            required: true
            default: "secretkey"
          server:
            description: server hostname
            required: true
            default: "server"
          cmd_args:
            description: test to run
            required: true

jobs:
    run:
        runs-on: ubuntu-latest
        steps:
        - name: invoke go action
          uses: mattkasun/test/.github/actions/test-action@master
          with:
            MASTERKEY: ${{ inputs.masterkey }}
            cmd_args: ${{ inputs.cmd_args }}
          env:
            DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_TOKEN }}
            KEY: ${{ secrets.TESTING_SSH_KEY }}
            MASTERKEY: ${{ inputs.masterkey }}
            TAG: ${{ inputs.tag }}
            API: ${{ inputs.api }}
            NETWORK: ${{ inputs.network }}
            SERVER: ${{ inputs.server }}
    docker:
        runs-on: ubuntu-latest
        steps:
        - name: docker
          uses: mattkasun/test/.github/actions/docker-action@master
          env:
            DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_TOKEN }}
            MASTERKEY: ${{ inputs.masterkey }}
            KEY: ${{ secrets.TESTING_SSH_KEY }}
    composite:
        runs-on: ubuntu-latest
        name: composite
        steps:
          - uses: actions/checkout@v4
          - id: foo
            uses: mattkasun/test/.github/actions/composite@master
            with:
             role: ${{ inputs.role }}
             duration: $(( inputs.duration ))


