name: Test Go Action

on: 
    workflow_dispatch:
        inputs:
            masterkey:
                description: server masterkey
                type: string
    
jobs:
    run:
        runs-on: ubuntu-latest
        steps:
        - name: invoke go action
          uses: mattkasun/test/.github/actions/test-action@master
          with:
            DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_TOKEN }}
            MASTERKEY: ${{ inputs.masterkey }}
