name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

 #   - name: Set up Go
 #     uses: actions/setup-go@v2
 #     with:
 #      go-version: 1.17

 #   - name: Build
 #     run: go build -v ./...
    - name: get files
      uses: dawidd6/action-download-artifact@v2
      with:
        repo: gravitl/devops
        workflow: .github/workflows/test.yml
        if_no_artifact_found: warn
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: list files
      run: |
        ls -la -R       

    - name: send message
      uses: appleboy/discord-action@master
      with:
        webhook_id: ${{ secrets.DISCORD_WEBHOOK_ID }}
        webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
        color: "#48f442"
        username: "GitHub Bot"
        message: "A new commit has been pushed with custom color."
        file: ./ping.log/testing-ping.log
