name: Example workflow yml

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Netmaker version'
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Package
      uses: bpicode/github-action-fpm@master
      with:
        fpm_args: './build'
        fpm_opts: '--debug -n mypackage -t deb -s dir'
    - name: Upload x86 to Release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: mypackage_1.0_amd64.deb
        tag: ${{ env.NETMAKER_VERSION }}
        overwrite: true
        prerelease: true
        asset_name: mypackage_1.0_amd64.deb
