name: remote release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'tag'
        required: true
jobs:
  call:
    uses: mattkasun/test2/.github/workflows/release.yml@main
    with:
      version: ${{ inputs.version }}
    secrets: inherit
    
  
