name: Test workflow

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Netmaker version'
        required: true
defaults:
    run:
      shell: bash
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.echo.outputs.tag }}
      version: ${{ steps.echo.outputs.version }}
    steps:
      - uses: actions/checkout@v2
      - name: Get Version Number
        run: |
          if [[ -n "${{ github.event.inputs.version }}" ]]; then
            VERSION=${{ github.event.inputs.version }}
          else
            VERSION=$(curl -fsSL https://api.github.com/repos/gravitl/netmaker/tags | grep 'name' | head -1 | cut -d'"' -f4)
          fi
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          #remove everything but digits and . from version for packaging purposes
          PACKAGE_VERSION=$(echo ${VERSION} | tr -cd '[:digit:].')
          echo "PACKAGE_VERSION=${PACKAGE_VERSION}" >> $GITHUB_ENV
      - name: Echo
        id: echo
        run: |
          echo ${{ env.VERSION }}
          echo "::set-output name=tag::${{ env.VERSION }}"
          echo ${{ env.PACKAGE_VERSION }}
          echo "::set-output name=version::${{ env.PACKAGE_VERSION }}"
  packages:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Set variables
        run: |
          echo ${{ needs.build.outputs.tag }} ${{ needs.build.outputs.version }}
          if [[ -n "${{ needs.build.outputs.tag }}" ]]; then
            echo "tag is set"
            ONE=${{needs.build.outputs.tag}}
          else
            echo "failure: tag not set"
            exit 1
          fi
          echo "VERSION=${ONE}" >> $GITHUB_ENV
          if [[ -n "${{ needs.build.outputs.version }}" ]]; then
            PACKAGE_VERSION=${{needs.build.outputs.version}}
          else
            echo "failure: version not set"
            exit 1
          fi
          echo "PACKAGE_VERSION=${PACKAGE_VERSION}" >> $GITHUB_ENV
          echo ${{ env.VERSION }}
          echo ${{ env.PACKAGE_VERSION }}
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2.0.0
        with:
          token: ${{ secrets.PERS_TOKEN_FOR_NETMAKER_DEVOPS}}
          respository: respository
          event-type: gravitl/netmaker-devops
          payload: '{"VERSION": " {{ env.PACKAGE_VERSION }}"}' 