name: Release Netmaker-UI
on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: string

jobs:

  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: mattkasun/test
          ref: develop
      - name: Setup git
        run: |
          git config --global user.name "nusak"
          git config --global user.email "mkasun@nusak.ca"
      - name: Create Release Branch
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git switch -c release-${{ inputs.version }}
          git tag -f ${{ inputs.version }}
          git push origin release-${{ inputs.version }}
          git push origin ${{ inputs.version }}
          gh release create ${{ inputs.version }} --notes-file release.md --latest --target release-test --verify-tag


  pull-request:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: create pr
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api --method POST \
          -H 'Accept: application/vnd.github+json' -H 'X-GitHub-Api-Version: 2022-11-28'  \
          /repos/mattkasun/test/pulls \
          -f title='${{ inputs.version }}' \
          -f head='release-${{ inputs.version }}' \
          -f base="master"
