name: Delete Droplets

on:
  workflow_run:
    workflows: [Debugging]
    types:
      - completed

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: echo vars
        run: |
          echo workflow_run ${{ github.event.workflow_run }}
          echo run_id ${{ github.event.workflow_run.run_id }}
          echo run_attempt ${{ github.event.workflow_run.run_attempt }}
          echo run_number ${{ github.event.workflow_run.run_number }}
          echo id ${{ github.event.workflow_run.id }}
        env:
          DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_TOKEN }}
          TAG: ${{ github.event.workflow_run.run_id }}-${{ github.event.workflow_run.run_attempt }}
